#!/usr/bin/env bash
set -euo pipefail

# Generate `mediamtx/mediamtx.yml` from `.env`.
#
# MediaMTX is optional (compose profile `rtsp-proxy`). It can be useful if you want:
# - a stable internal RTSP endpoint (even if the camera URL changes)
# - on-demand pulling so the camera isn't continuously streamed
# - a single place to store RTSP URLs (still in `.env`, not in git)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "${SCRIPT_DIR}/_lib.sh"

load_env
require_vars CAMERA_HOST CAMERA_USER CAMERA_PASS RTSP_MAIN_PATH RTSP_SUB_PATH

ROOT="$(repo_root)"
OUT_DIR="${ROOT}/mediamtx"
OUT_FILE="${OUT_DIR}/mediamtx.yml"

MAIN_URL="rtsp://${CAMERA_USER}:${CAMERA_PASS}@${CAMERA_HOST}:554${RTSP_MAIN_PATH}"
SUB_URL="rtsp://${CAMERA_USER}:${CAMERA_PASS}@${CAMERA_HOST}:554${RTSP_SUB_PATH}"

mkdir -p "${OUT_DIR}"

cat > "${OUT_FILE}" <<EOF
# Generated by scripts/gen_mediamtx_config.sh
logLevel: info

paths:
  reolink_main:
    source: ${MAIN_URL}
    sourceOnDemand: yes
  reolink_sub:
    source: ${SUB_URL}
    sourceOnDemand: yes
EOF

echo "Wrote: ${OUT_FILE}"
echo "Use with: docker compose --profile rtsp-proxy up -d"
