# register_kb_tracker_task.ps1
# Registers a Windows Task Scheduler task that starts the keyboard/mouse
# activity tracker at login. Run once as Administrator.

$ScriptDir = "C:\Github\tools\keyboard-tracker"
$LaunchScript = "$ScriptDir\launch_kb_tracker.ps1"

# Read AIHUB_TOKEN from WSL .env (if set)
$token = ""
try {
    $token = (wsl cat /home/sajden/github/ai-cam/.env 2>$null) |
             Where-Object { $_ -match "^AIHUB_TOKEN=(.+)" } |
             ForEach-Object { $Matches[1] } |
             Select-Object -First 1
} catch {}

# Write the launcher script
$lines = @(
    '# Auto-generated by register_kb_tracker_task.ps1 — do not edit manually',
    '$env:AIHUB_URL = "http://localhost:8080"',
    '$env:AIHUB_TOKEN = "' + $token + '"',
    '$env:IDLE_THRESHOLD_SEC = "300"',
    '$env:REPORT_INTERVAL_SEC = "30"',
    '$env:DEVICE_NAME = "windows-kb"',
    'python C:\Github\tools\keyboard-tracker\activity_tracker.py'
)
[System.IO.File]::WriteAllText($LaunchScript, ($lines -join "`r`n") + "`r`n")
Write-Host "Wrote $LaunchScript"

# Register Task Scheduler task
$taskName = "AiHub-KeyboardTracker"
$action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NonInteractive -WindowStyle Hidden -File `"$LaunchScript`""
$trigger = New-ScheduledTaskTrigger -AtLogOn
$settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit 0 -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)

Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -RunLevel Highest
Write-Host "Task '$taskName' registered — starts at login."
Write-Host "Starting now..."
Start-ScheduledTask -TaskName $taskName
